use core::time;

type Color = i32;
type Attr = i32;
type EventType = isize;
type FillReturn = isize;
type BorderCharacter = char;

pub enum BorderShape {
    BorderUndefined,
    BorderNone,
    BorderRounded,
    BorderSharp,
    BorderBold,
    BorderBlock,
    BorderThinBlock,
    BorderDouble,
    BorderHorizontal,
    BorderVertical,
    BorderTop,
    BorderBottom,
    BorderLeft,
    BorderRight,
}

pub enum Keystrokes {
    Ctrl_A,
    Ctrl_B,
    Ctrl_C,
    Ctrl_D,
    Ctrl_E,
    Ctrl_F,
    Ctrl_H,
    Tab,
    Ctrl_J,
    Ctrl_K,
    Ctrl_L,
    Ctrl_M,
    Ctrl_N,
    Ctrl_O,
    Ctrl_P,
    Ctrl_Q,
    Ctrl_R,
    Ctrl_S,
    Ctrl_T,
    Ctrl_U,
    Ctrl_V,
    Ctrl_W,
    Ctrl_X,
    Ctrl_Y,
    Ctrl_Z,
    Esc,
    Ctrl_Space,
    Ctrl_Del,
    Ctrl_Backslash,
    Ctrl_Caret,
    Ctrl_Slash,
    Shift_Tab,
    Backspace,
    Del,
    PageUp,
    PageDown,
    Up,
    Down,
    Left,
    Right,
    Home,
    End,
    Ins,
    Shift_Up,
    Shift_Down,
    Shift_Left,
    Shift_Right,
    Shift_Delete,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Alt_Backspace,
    Alt_Up,
    Alt_Down,
    Alt_Left,
    Alt_Right,
    Alt_Shift_Up,
    Alt_Shift_Down,
    Alt_Shift_Left,
    Alt_shift_Right,
    Alt,
    Ctrl_Alt,
    Invalid,
    Fatal,
    Mouse,
    DoubleClick,
    LeftClick,
    RightClick,
    ScrollUp,
    ScrollDown,
    Shift_LeftClick,
    Shift_RightClick,
    Shift_ScrollUp,
    Shift_ScrollDown,
}

pub enum Events {
    Resize,
    Change,
    BackendEOF,
    Start,
    Load,
    Focus,
    One,
    Zero,
    Result,
    Jump,
    JumpCancel,
    ClickHeader,
}

pub struct ColorPair {
    fg:   Color,
    bg:   Color,
    attr: Attr,
} 

pub struct ColorAttr {
    color: Color,
    attr:  Attr,
} 

pub struct ColorTheme {
    colored:        bool,
    input:          ColorAttr,
    disabled:       ColorAttr,
    fg:             ColorAttr,
    bg:             ColorAttr,
    selected_fg:    ColorAttr,
    selected_bg:    ColorAttr,
    selected_match: ColorAttr,
    preview_fg:     ColorAttr,
    preview_bg:     ColorAttr,
    dark_bg:        ColorAttr,
    gutter:         ColorAttr,
    prompt:         ColorAttr,
    matches:        ColorAttr,
    current:        ColorAttr,
    current_match:  ColorAttr,
    spinner:        ColorAttr,
    info:           ColorAttr,
    cursor:         ColorAttr,
    marker:         ColorAttr,
    header:         ColorAttr,
    separator:      ColorAttr,
    scrollbar:      ColorAttr,
    border:         ColorAttr,
    preview_border: ColorAttr,
    preview_scroll: ColorAttr,
    border_label:   ColorAttr,
    preview_label:  ColorAttr,
}

pub struct Event {
    typ:         EventType,
    rune:        char,
    mouse_event: *mut MouseEvent,
}

pub struct MouseEvent {
    y:      isize,
    x:      isize,
    s:      isize,
    left:   bool,
    down:   bool,
    double: bool,
    module: bool,
}

pub struct BorderStyle {
    shape:        BorderShape,
    top:          char,
    bottom:       char,
    left:         char,
    right:        char,
    top_left:     char,
    top_right:    char,
    bottom_left:  char,
    bottom_right: char,
}

pub struct TermSize {
    lines:     isize,
    columns:   isize,
    px_width:  isize,
    pw_height: isize,
}

pub struct FullscreenRenderer {
    theme:       *mut ColorTheme,
    mouse:       bool,
    force_black: bool,
    pv_downtime: time::Duration,
    clicks:      [[isize;2]],
}

fn make_border_style(shape: BorderShape, utf: bool) -> BorderStyle {
    if !utf {
        return BorderStyle {
            shape:        shape,
            top:          '-',
            bottom:       '-',
            left:         '|',
            right:        '|',
            top_left:     '+',
            top_right:    '+',
            bottom_left:  '+',
            bottom_right: '+',
        }
    }
    match shape {
        BorderShape::BorderSharp => return BorderStyle {
            shape:        shape,
            top:          '─',
            bottom:       '─',
            left:         '│',
            right:        '│',
            top_left:     '┌',
            top_right:    '┐',
            bottom_left:  '└',
            bottom_right: '┘',  
        },
        BorderShape::BorderBold => return BorderStyle {
            shape:        shape,
            top:          '━',
            bottom:       '━',
            left:         '┃',
            right:        '┃',
            top_left:     '┏',
            top_right:    '┓',
            bottom_left:  '┗',
            bottom_right: '┛',  
        },
        BorderShape::BorderBlock => return BorderStyle {
            shape:        shape,
            top:          '▀',
            bottom:       '▄',
            left:         '▌',
            right:        '▐',
            top_left:     '▛',
            top_right:    '▜',
            bottom_left:  '▙',
            bottom_right: '▟',  
        },
        BorderShape::BorderThinBlock => return BorderStyle {
            shape:        shape,
            top:          '▔',
            bottom:       '▁',
            left:         '▏',
            right:        '▕',
            top_left:     '🭽',
            top_right:    '🭾',
            bottom_left:  '🭼',
            bottom_right: '🭿',  
        },
        BorderShape::BorderDouble => return BorderStyle {
            shape:        shape,
            top:          '═',
            bottom:       '═',
            left:         '║',
            right:        '║',
            top_left:     '╔',
            top_right:    '╗',
            bottom_left:  '╚',
            bottom_right: '╝',  
        },
 
        _ => return BorderStyle {
            shape:        shape,
            top:          '─',
            bottom:       '─',
            left:         '│',
            right:        '│',
            top_left:     '╭',
            top_right:    '╮',
            bottom_left:  '╰',
            bottom_right: '╯',  
        },

    }
} 
